### ISSUE TITLE
Drop OMT dependency by using this.emitFile?

### ISSUE THREAD

**Issue by eight04** [surma/rollup-plugin-comlink#2]
Is it possible to drop OMT dependency by emitting the wrapper chunk via `this.emitFile` and reference the path using `import.meta.ROLLUP_FILE_referenceId`?

https://rollupjs.org/guide/en/#thisemitfileemittedfile-emittedchunk--emittedasset--string

**Comment by surma** [comment]
Not yet, sadly. The OMT plugin is necessary for as long as we don’t have full support for module workers in every browser as OMT injects a tiny AMD loader. Once browsers have caught up, the entire OMT plugin will become pretty much obsolete (and I can’t wait!).
